src/Entity/Opportunity.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Opportunity
{
    


      /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Projet", inversedBy="opportunities")
     * @ORM\JoinColumn(nullable=true)
     */
    private $projet;


    public function getProjet(): ?Projet
    {
        return $this->projet;
    }

    public function setProjet(?Projet $projet): self
    {
        $this->projet = $projet;

        return $this;
    }

 
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string")
     */
    private $city;

    /**
     * @ORM\Column(type="float")
     */
    private $budget;

    /**
     * @ORM\Column(type="float")
     */
    private $monthlyProfit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): void
    {
        $this->city = $city;
    }

    public function getBudget(): ?float
    {
        return $this->budget;
    }

    public function setBudget(float $budget): void
    {
        $this->budget = $budget;
    }

    public function getMonthlyProfit(): ?float
    {
        return $this->monthlyProfit;
    }

    public function setMonthlyProfit(float $monthlyProfit): void
    {
        $this->monthlyProfit = $monthlyProfit;
    }

    public function getAnnualProfit(): ?float
    {
        return $this->monthlyProfit * 12;
    }

    public function getProfitPercentage(): ?float
    {
        return ($this->monthlyProfit / $this->budget) * 100;
    }

    

}

src/Controller/ProfController.php
<?php

namespace App\Controller;


use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Entity\User; 
use App\Entity\Opportunity; 
use App\Entity\Projet; 
use Doctrine\ORM\EntityManagerInterface;
use App\Form\ProjetType;
use Doctrine\ORM\Mapping as ORM;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\Security;


#[Route(path: '/prof')]
class ProfController extends AbstractController
{
    #[Route('/eleves', name: 'app_prof')]
 
    public function index(Request $request, UserRepository $userRepository,EntityManagerInterface $entityManager): Response
    {
        
         // Vérifiez si l'utilisateur est authentifié
         if ($this->isGranted('ROLE_CLIENT')) {
            // Redirigez vers la page de connexion
            $projets = $entityManager->getRepository(Projet::class)->findAll();

            return $this->render('prof/index.html.twig', ["projets"=> $projets]);
        }
        // Vérifiez si l'utilisateur est authentifié
        if ($this->isGranted('ROLE_MANAGER')) {
        
        $projets = $entityManager->getRepository(Projet::class)->findAll();

        return $this->render('prof/index.html.twig', ["projets"=> $projets]);
        
    }
        return $this->redirectToRoute('app_login');
    }



 /**
     * @Route("/choisir", name="choisir")
     */
    public function analysesAction(Request $request): JsonResponse
    {
        // Votre logique pour la page d'analyses ici
        $data = [
            'message' => "Merci pour votre choix, l'application est actuellemnt en etat de productions"
        
        ];
        
        return $this->json($data);
    }


     /**
     * @Route("/mon_liste", name="mon_liste")
     */
    public function monListe(Request $request): Response
    {
        $user = $this->getUser();
        $projets = $user->getProjets(); 
        return $this->render('prof/client_projects_list.html.twig', ["projets" => $projets]);
    }


     /**
     * @Route("/opportunity/{id}", name="opportunity")
     */
    public function ajouterAnalyse(Request $request, EntityManagerInterface $entityManager, $id): Response
    {
        $opportunity = $entityManager->getRepository(Opportunity::class)->find($id);

        if (!$opportunity) {
            throw $this->createNotFoundException('Opportunity not found');
        }

        return $this->render('prof/opportunity.html.twig', [
            'opportunity' => $opportunity,
        ]);
    }

      /**
     * @Route("/projet/{id}", name="projet")
     */
    public function projet(Request $request, EntityManagerInterface $entityManager, $id): Response
    {
        $projet = $entityManager->getRepository(Projet::class)->find($id);

        if (!$projet) {
            throw $this->createNotFoundException('Projet not found');
        }

        return $this->render('prof/project.html.twig', [
            'projet' => $projet,
        ]);
    }  
    
    
    
    /**
     * @Route("/opportunity-list", name="opportunity_list")
     *  @IsGranted("ROLE_MANAGER")
     */
    public function listOpportunities(EntityManagerInterface $entityManager): Response
    {
       
        $opportunities = $entityManager->getRepository(Opportunity::class)->findAll();

        return $this->render('prof/list_of_available_opportunities.html.twig', [
            'opportunities' => $opportunities,
        ]);
    }


     /**
     * @Route("/projet_list", name="projet_list")
     */
    public function listProjet(EntityManagerInterface $entityManager): Response
    {
       
        $projets = $entityManager->getRepository(Projet::class)->findAll();

        return $this->render('prof/list_of_available_projects.html.twig', [
            'projets' => $projets,
        ]);
    }

    /**
     * @Route("/new-project", name="new_project")
     */
    public function nouveauProjet(Request $request, EntityManagerInterface $entityManager)
    {
        $projet = new Projet();
        $form = $this->createForm(ProjetType::class, $projet);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser(); // Récupérer l'utilisateur connecté
            $projet->setUser($user);   // Assigner l'utilisateur au projet
            $entityManager->persist($projet);
            $entityManager->flush();
            
            // Rediriger vers une page après l'enregistrement
            return $this->redirectToRoute('app_prof'); // Remplacez 'app_prof' par la route souhaitée
        }
        
        return $this->render('prof/project_form.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/opportunities/{userId}", name="opportunities_for_user")
    */
    public function opportunitiesForUser($userId)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $user = $entityManager->getRepository(User::class)->find($userId);

        if (!$user) {
            throw $this->createNotFoundException('User not found');
        }

        $userOpportunities = $user->getOpportunities();

        
    }


    
    /**
     * @Route("/add-project/{id}", name="add_project")
    */
    public function ajouterProjet (Request $request, Projet $projet, EntityManagerInterface $entityManager) : Response
    {
       
        $user = $this->getUser(); // Récupérer l'utilisateur connecté
        $projet->setUser($user);   // Assigner l'utilisateur au projet
        $user->addProjet($projet); 
        $projets = $user->getProjets(); 
        $entityManager->persist($projet);
        $entityManager->persist($user);
        $entityManager->flush();
        return $this->render('prof/client_projects_list.html.twig', ["projets" => $projets]);
        
    }

   /**
     * @Route("/associate-opportunity/{projetId}/{opportuniteId}", name="associate_opportunity")
     */
    public function associerOpportunite(Request $request, $projetId ,$opportuniteId, EntityManagerInterface $entityManager)
    {      

        // Récupérer les entités à partir de leurs IDs
        $projet = $entityManager->getRepository(Projet::class)->find($projetId);
        $opportunite = $entityManager->getRepository(Opportunity::class)->find($opportuniteId);
        if (!$opportunite) {
            throw $this->createNotFoundException('Opportunité non trouvée.');
        }
        if (!$projet) {
            throw $this->createNotFoundException('Projet non trouvé.');
        }
        

        // Associer l'opportunité au projet
        $projet->addOpportunity($opportunite);

        $entityManager->flush();

        return $this->redirectToRoute('mon_liste');
    }


    /**
     * @Route("/projets-ajax", name="projets_ajax")
     */
    public function projetsAjax(EntityManagerInterface $entityManager)
    {
        $projets = $entityManager->getRepository(Projet::class)->findAll();

        $projetsArray = [];
        foreach ($projets as $projet) {
            $projetsArray[] = [
                'id' => $projet->getId(),
                'nom' => $projet->getTitre(),
            ];
        }
        
        return new JsonResponse($projetsArray);
    }


       /**
     * @Route("associate-opportunity-show/{opportunityId}", name="associate_opportunity_show")
     */
    public function associerOpportuniteShow(Request $request, $opportunityId, EntityManagerInterface $entityManager)
    {
        $selectedId = 0;
        $opportunity = $entityManager->getRepository(Opportunity::class)->find($opportunityId);
        return $this->render('prof/associate_opportunity.html.twig', ["opportunity" => $opportunity, "projetId"=>$selectedId]);
    }
    

}

templates/prof/associate_opportunity.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Choisir un projet</title>
    <!-- Ajouter les liens vers les fichiers Bootstrap CSS et jQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <h1>Choisir un projet</h1>
            </div>
            <div class="card-body">
                <label for="projet-select">Sélectionnez un projet :</label>
                <select id="projet-select" class="form-control">
                    <option value="">Sélectionnez un projet</option>
                </select>
                <p id="projet-details" class="mt-3"></p>
                <a href="#" id="associer-link" class="btn btn-success float-right">Associer Opportunité</a>
            </div>
        </div>
    </div>

    <script>
    $(document).ready(function() {
        $.ajax({
            url: "{{ path('projets_ajax') }}",
            type: "GET",
            dataType: "json",
            success: function(data) {
                var select = $('#projet-select');
                var details = $('#projet-details');
                var associerLink = $('#associer-link');

                data.forEach(function(projet) {
                    var option = $('<option>', {
                        value: projet.id,
                        text: projet.nom
                    });
                    select.append(option);
                });

             select.on('change', function() {
    var selectedId = $(this).val();
    console.log("l'id du projet  : "+selectedId); 
    console.log("l'id de l'oportunity : "+ {{opportunity.id}});
    var lienAssocier = document.getElementById('associer-link');
    lienAssocier.href ="{{ path('associate_opportunity', {projetId : 1 , opportuniteId : opportunity.id }) }}"

     });

            }
        });
    });
    </script>

    <!-- Ajouter le lien vers le fichier Bootstrap JS à la fin du body -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/prof/authentification.html.twig
{# templates/login.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Login</h1>

 <form action="{{ path('app_login') }}" method="post">
 
    <label for="">Email</label>
    <input type="text" required name= "_username">
    <label for="">Password</label>
    <input type="password" required name= "_password">
    <button type = "submit">Connexion</button>
 </form>

{% endblock %}

templates/prof/client_projects_list.html.twig
{# templates/projet_list.html.twig #}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock %}


{% block body %}
    <div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <span class="nav-link">Email: {{ app.user.email }}</span>
        </li>
        <li class="nav-item">
            <span class="nav-link">Role: {{ app.user.roles[0] }}</span>
        </li>
    </ul>
</nav>

        <h1>Liste des Projets</h1>
        <a href= {{path("app_prof")}} class="btn btn-success bottom-right-button">Retourner à la recherche</a>

        <div class="card-deck">
            {% for projet in projets %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h3 class="card-title">{{ projet.titre }}</h3>
                        <p class="card-text">{{ projet.description }}</p>
                        <p class="card-text">
                            <strong>Opportunités associées :</strong>
                            {% if projet.opportunities is empty %}
                                Aucune opportunité associée
                            {% else %}
                                <ul class="list-group">
                                    {% for opportunite in projet.opportunities %}
                                        <li class="list-group-item"><a href="{{ path('opportunity', {'id': opportunite.id}) }}">{{ opportunite.title }}</a></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/prof/index.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Parmi ces projets innovants, Choisissez le votre !</title>
  <!-- Importation des fichiers Bootstrap via CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

{% block body %}
<body>
  <div class="container">
    <div class="d-flex justify-content-center">
        <h1>Choisi ton projet</h1>
    </div>
       <form method="POST" action="">
            <div class="form-group">
                <label for="langue">Choisissez la langue :</label>
                <select class="form-control" name="langue" id="langue">
                    <option value="fr">Français</option>
                    <option value="ar">العربية</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Changer</button>
        </form>

    <div class="row">
     {% for projet in projets %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{{ asset('images/boutique.png') }}"  class="card-img-top img-fluid" alt="Image 1" style = "height : 200px; " >
          <div class="card-body" style="height: 200px; overflow-y: auto;">
            <h5 class="card-title">{{projet.titre}}</h5>
            <p class="card-text">
              {{projet.description}}
            </p>

          </div>
          <a href= {{path("projet", {'id' : projet.id})}} class="btn btn-success">Choisir</a> 

        </div>
      </div>
      {% endfor %}
      <!-- Ajoutez d'autres colonnes ici -->

    </div>
        
  <a href= "{{path("mon_liste")}}" class="btn btn-warning">Mes projets</a>
  {% if is_granted('ROLE_MANAGER') %}
    <a href="{{ path('opportunity_list') }}" class="btn btn-warning">Aller à la liste des opportunités</a>
    <a href="{{ path('opportunity_list') }}" class="btn btn-warning">Aller à la liste des projets</a>
    <a href="{{ path('opportunity_list') }}" class="btn btn-warning">Aller à la liste des clients</a>
    <a href="{{ path('new_project') }}" class="btn btn-warning">+Creer un projet</a>

{% endif %}

    <!-- Cadre pour la vidéo de présentation -->
    <div class="embed-responsive embed-responsive-16by9" style="position: fixed; bottom: 20px; right: 20px; width: 300px;">
      <iframe class="embed-responsive-item" src="{{ asset('images/exemple_video.mp4') }}" allowfullscreen style="width: 100%; height: 100%;"></iframe>
    </div>
  </div>
  <a href="{{ path('app_logout') }}" class="btn btn-danger">Déconnexion</a>


  <!-- Importation des fichiers JavaScript Bootstrap via CDN -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>
{% endblock %}

templates/prof/list_of_available_opportunities.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Opportunity List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Center the card */
        .center-card {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* You can adjust this as needed */
        }
        
        /* Style the red percentage value */
        .red-percentage {
            color: red;
        }
    </style>
</head>
<body>
    {% for opportunity in opportunities %}
    <div class="center-card">
            {% include 'prof/opportunity.html.twig' with {"opportunity" : opportunity} %} 
    </div>
    {% endfor %}
</body>
</html>

templates/prof/list_of_available_projects.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Projet List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Center the card */
        .center-card {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* You can adjust this as needed */
        }
        
        /* Style the red percentage value */
        .red-percentage {
            color: red;
        }
    </style>
</head>
<body>
    {% for projet in projets %}
    <div class="center-card">
            {% include 'prof/projet.html.twig' with {"projet" : projet} %} 
    </div>
    {% endfor %}
</body>
</html>

templates/prof/opportunity.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Opportunity Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Center the card */
        .center-card {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* You can adjust this as needed */
        }
        
        /* Style the red percentage value */
        .red-percentage {
            color: red;
        }

        /* Style the green button */
        .green-button {
            position: absolute;
            bottom: 20px;
            right: 20px;
        }
    </style>
</head>
<body>
    <div class="center-card">
        <div class="card" style="width: 40rem; height : 25rem; ">
            <div class="card-body">
                <h5 class="card-title">{{ opportunity.title }}</h5>
                <p class="card-text">{{ opportunity.description }}</p>
                <p class="card-text"><strong>City:</strong> {{ opportunity.city }}</p>
                <p class="card-text"><strong>Budget:</strong> ${{ opportunity.budget }}</p>
                <p class="card-text"><strong>Monthly Profit:</strong> ${{ opportunity.monthlyProfit }}</p>
                <p class="card-text"><strong>Annual Profit:</strong> ${{ opportunity.annualProfit }}</p>
                <p class="card-text"><strong>Profit Percentage:</strong>
                    <span class="red-percentage">{{ opportunity.profitPercentage }}%</span>
                </p>
                <!-- Green button -->
                <a href = {{path('associate_opportunity_show', {'opportunityId' : opportunity.id})}} class="btn btn-success green-button">On y va ! </a>
            </div>
        </div>
    </div>
</body>
</html>

templates/prof/project.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Projet Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Center the card */
        .center-card {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* You can adjust this as needed */
        }
        
        /* Add a scroll bar to the card body */
        .card-body-scroll {
            max-height: 300px; /* Adjust the maximum height as needed */
            overflow: auto;
        }

        /* Position the button at the bottom-right */
        .bottom-right-button {
            position: absolute;
            bottom: 10px;
            right: 10px;
        }
    </style>
</head>
<body>
    <div class="center-card">
        <div class="card" style="width: 40rem; position: relative;">
            <div class="card-body card-body-scroll">
                <h5 class="card-title">{{ projet.titre }}</h5>
                <p class="card-text">{{ projet.description }}</p>
                <p class="card-text"><strong>Budget Max:</strong> ${{ projet.budgetMax }}</p>
                <p class="card-text"><strong>Budget Min:</strong> ${{ projet.budgetMin }}</p>
                <p class="card-text"><strong>Pourcentage de Rentabilité:</strong> {{ projet.pourcentageRentabilite }}%</p>
                <p class="card-text"><strong>Villes:</strong> {{ projet.villes|join(', ') }}</p>
            </div>
            <a href= {{path("add_project", {'id' : projet.id})}} class="btn btn-success bottom-right-button">Lancer la recherche</a>
        </div>
    </div>
</body>
</html>

templates/prof/project_form.html.twig
{# templates project_form.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h1 class="card-title">Créer un nouveau projet</h1>
                    </div>
                    <div class="card-body">
                        {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.titre) }}
                            {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.description) }}
                            {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.budgetMax) }}
                            {{ form_widget(form.budgetMax, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.budgetMin) }}
                            {{ form_widget(form.budgetMin, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.pourcentageRentabilite) }}
                            {{ form_widget(form.pourcentageRentabilite, {'attr': {'class': 'form-control'}}) }}
                        </div>
                       
                    
                        
                        <button type="submit" class="btn btn-primary">Créer</button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/prof/student.html.twig
<p>{{etudiant.nom}}</p>